BankOfSecurities/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from BankOfSecurities import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('depositor.urls')),
    path('', include('accounts.urls')),
    path('', include('bonds.urls')),
    path('', include('portfolio.urls')),
    path('', include('transaction.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bonds/urls.py
from django.urls import path, re_path

from .views import *


urlpatterns = [
    path('bonds-create/', BondsCreateView.as_view(), name='bonds-create'),
    path('currency-type-create/', CurrencyTypeCreateView.as_view(), name='currency-type-create'),
    path('market/bonds/', BondsMarketView.as_view(), name='bonds-list'),
    path('market/bonds/<slug:bonds_slug>/', DetailBondsView.as_view(), name='bonds-detail'),
    # path('logout/', logout_user, name='logout'),
]

bonds/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class CurrencyType(models.Model):
    name = models.CharField(max_length=255, verbose_name="Назва")
    photo = models.ImageField(upload_to="photos/currencyType/", verbose_name="Фото")

    class Meta:
        verbose_name = 'Тип валюти'
        verbose_name_plural = 'Типи валют'

    def __str__(self):
        return self.name


class Bonds(models.Model):
    YTM = models.BooleanField(verbose_name="Дохід до погашення", default=True, blank=True)
    name = models.CharField(max_length=255, verbose_name="Номер", )
    currency_type = models.ForeignKey(CurrencyType, on_delete=models.CASCADE, verbose_name="Тип валюти")
    quantity = models.IntegerField(verbose_name="Кількість", )
    repayment_date = models.DateTimeField(auto_now=False, verbose_name="Дата розміщення")
    denomination = models.DecimalField(verbose_name="Номінал", max_digits=9, decimal_places=2)
    placement_period = models.DateTimeField(auto_now=False, verbose_name="Дата погашення")
    coupon_rate = models.FloatField(verbose_name="Ставка купона", )
    number_payment = models.IntegerField(verbose_name="Кількість виплати купона", default=1,  blank=True)
    slug = models.SlugField(unique=True, db_index=True, verbose_name="URL")

    class Meta:
        verbose_name = 'Облігації'
        verbose_name_plural = verbose_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.YTM and self.number_payment is None:
            raise ValidationError('Якщо YTM встановлено в True, поле "Кількість виплати купона" обов\'язкове.')
        elif self.YTM is None and self.number_payment:
            raise ValidationError('Якщо YTM встановлено в Fslse, поле "Кількість виплати купона" не обов\'язкове.')

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('bonds-detail', kwargs={'bonds_slug': self.slug})

    def __str__(self):
        return self.name

transaction/models.py
from django.db import models

from accounts.models import User
from bonds.models import Bonds
from utils.transfer_types import TRANSFER_TYPES


class Transaction(models.Model):
    transfer_type = models.CharField(max_length=50, choices=TRANSFER_TYPES)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=15, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Транзакція"
        verbose_name_plural = "Транзакції"

    def __str__(self):
        return self.transfer_type + ' ' + str(self.price) + ' ' + str(self.date)


class Bargain(models.Model):
    transaction = models.OneToOneField(Transaction, on_delete=models.CASCADE)
    bonds = models.ForeignKey(Bonds, on_delete=models.CASCADE)
    count = models.IntegerField(verbose_name="Кількість")

    class Meta:
        verbose_name = "Угода"
        verbose_name_plural = "Угоди"

bonds/forms.py
# forms.py
from django import forms
from .models import Bonds, CurrencyType


class CurrencyTypeCreateForm(forms.ModelForm):
    class Meta:
        model = CurrencyType
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-input'  # Додає клас 'form-input' для всіх полів
            field.widget.attrs['placeholder'] = field.label  # Встановлює placeholder як ім'я поля


class BondsCreateForm(forms.ModelForm):
    YTM = forms.BooleanField(label="YTM")
    name = forms.CharField(max_length=100)
    currency_type = forms.ModelChoiceField(queryset=CurrencyType.objects.all())
    quantity = forms.IntegerField()
    repayment_date = forms.DateTimeField(input_formats=['%d/%m/%y'])
    denomination = forms.FloatField()
    placement_period = forms.DateTimeField(input_formats=['%d/%m/%y'])
    coupon_rate = forms.FloatField()
    number_payment = forms.IntegerField()

    class Meta:
        model = Bonds
        fields = ['YTM', 'name', 'currency_type', 'quantity', 'repayment_date', 'denomination', 'placement_period',
                  'coupon_rate', 'number_payment']


class BuyBondsForm(forms.Form):
    count = forms.IntegerField(label="Кількість")

bonds/views.py
import requests
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, DetailView, FormView

from bonds.forms import BondsCreateForm, CurrencyTypeCreateForm, BuyBondsForm
from bonds.models import Bonds
from bonds.services import get_bonds_list, get_bonds, get_payment_table, get_bond_headers, get_payment_days_headers, \
    gen_buy_bonds_trans
from utils.utils import DataMixin


class CurrencyTypeCreateView(DataMixin, CreateView):
    template_name = 'bonds/currency_type_create.html'

    form = CurrencyTypeCreateForm()
    context = {
        'form': form,
    }

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name, context=self.context)

    def post(self, *args, **kwargs):
        post_form = CurrencyTypeCreateForm(self.request.POST, self.request.FILES)
        print(post_form)
        if post_form.is_valid():

            post_form.save()
            return redirect('login')
        return render(self.request, self.template_name, context=self.context)


class BondsCreateView(DataMixin, CreateView):
    template_name = 'bonds/bonds_create.html'

    bonds_form = BondsCreateForm()
    context = {
        'form': bonds_form,
    }

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name, context=self.context)

    def post(self, *args, **kwargs):
        bonds_form = BondsCreateForm(self.request.POST)
        print(bonds_form)
        if bonds_form.is_valid():
            bonds_form.save()
            return redirect('login')
        return render(self.request, self.template_name, context=self.context)


class BondsMarketView(DataMixin, ListView):
    model = Bonds
    template_name = 'bonds/bonds_list.html'
    paginate_by = 50

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Ринок")
        context['headers'] = get_bond_headers()
        context['bonds'] = get_bonds_list()
        return dict(list(context.items()) + list(c_def.items()))


class DetailBondsView(DataMixin, DetailView, FormView):
    model = Bonds
    template_name = 'bonds/bonds_detail.html'
    slug_url_kwarg = 'bonds_slug'
    context_object_name = 'bond'
    form_class = BuyBondsForm

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title=str(self.object))
        context['bond_headers'] = get_bond_headers()
        context['payment_days_headers'] = get_payment_days_headers()
        context['bond'] = get_bonds(self.object)
        context['payment_days'] = get_payment_table(self.object)

        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form, **kwargs):
        count = form.cleaned_data['count']
        slug = form.data['slug']
        price = form.data['price']
        self.request.session['buy_bonds'] = gen_buy_bonds_trans(slug, count, price)
        self.request.session['attempt'] = 0
        return redirect('buy-bonds', bonds=self.kwargs['bonds_slug'])

templates/bonds/bonds_create.html
<form method="post" id="signup-form" class="signup-form">
     {% csrf_token %}
    <h2 class="form-title">Тип валюти</h2>
    {{ form.as_p }}
    <div class="form-group">
        <input type="submit" name="submit" id="submit" class="form-submit" value="Реєстрація"/>
    </div>
</form>

{% if form.errors %}
    <p>Є помилки у формі. Будь ласка, виправте їх.</p>
    {{ form.errors }}
{% endif %}

templates/bonds/bonds_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center ">
        <table class="table table-light w-50">
            <tbody>
                {% for header_key, header_value in bond_headers.items %}
                    <tr>
                        <th scope="row">{{ header_value }}</th>
                        {% for bond_key, bond_value in bond.items %}
                            {% if header_key == bond_key %}
                                <td>{{ bond_value }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="d-flex justify-content-center align-items-center ">
    <table class="table table-light w-50">
        <thead>
            <tr>
                {% for header in payment_days_headers.values %}
                    <th scope="col">{{ header }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for payment_date in payment_days %}
                <tr>
                    {% for key, value in payment_date.items %}
                        <td>{{ value }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>

    </div>
<form method="post">
        <div class="d-flex justify-content-center align-items-center w-50">
                {% csrf_token %}
                <div class="col-auto">
                    {{ form.as_p }}
                        <input type="hidden" id="id_slug" name="slug" value="{{ bond.slug }}">
                        <input type="hidden" id="id_price" name="price" value="{{ bond.price }}">
                </div>
            
                <div class="col-auto">
                    <button type="submit" name="submit" id="submit" class="btn btn-primary mb-3">Купити</button>
                </div>
            
        </div>
    </form>

{% endblock %}

templates/bonds/bonds_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center ">
    <table class="table table-light w-75" style="background: #fffffe;">
        <thead>
            <tr>
                {% for header in headers.values %}
                    <th scope="col">{{ header }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for bond in bonds %}
                <tr>
                    {% for key, value in bond.items %}
                        {% if key == 'name' %}
                            <td><a href="{{ bond.slug }}" class="link-secondary">{{ value }}</a></td>
                        {% elif key != 'slug' %}
                        	<td>{{ value }}</td>
                        {% endif %} 
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

templates/bonds/currency_type_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" href="{% static '/css/dep_register_style.css' %}" rel="stylesheet" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Тип валюти</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    </head>
<body>
    <div class="main">

        <section class="BondsCreate">
            <div class="container">
                <div class="signup-content">
                    <form method="POST" id="signup-form" class="signup-form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h2 class="form-title">Тип валюти</h2>
                        {{ form.as_p }}
                        <div class="form-group">
                            <input type="submit" name="submit" id="submit" class="form-submit" value="Реєстрація"/>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
</body>
</html>